//this is a generate file,do not modify it!
package keys

import (
	"github.com/nomos/go-lokas/protocol"
)

type MOUSE_EVENT_TYPE protocol.Enum 

const (
	MOUSE_EVENT_TYPE_NULL MOUSE_EVENT_TYPE  = 0 //NULL
	MOUSE_EVENT_TYPE_DOWN MOUSE_EVENT_TYPE  = 1 //DOWN
	MOUSE_EVENT_TYPE_UP MOUSE_EVENT_TYPE  = 2 //UP
	MOUSE_EVENT_TYPE_PRESS MOUSE_EVENT_TYPE  = 3 //PRESS
	MOUSE_EVENT_TYPE_SCROLL_UP MOUSE_EVENT_TYPE  = 4 //SCROLL_UP
	MOUSE_EVENT_TYPE_SCROLL_DOWN MOUSE_EVENT_TYPE  = 5 //SCROLL_DOWN
	MOUSE_EVENT_TYPE_MOVE MOUSE_EVENT_TYPE  = 6 //MOVE
	MOUSE_EVENT_TYPE_ENTER MOUSE_EVENT_TYPE  = 7 //ENTER
	MOUSE_EVENT_TYPE_LEAVE MOUSE_EVENT_TYPE  = 8 //LEAVE
	MOUSE_EVENT_TYPE_CANCEL MOUSE_EVENT_TYPE  = 9 //CANCEL
	MOUSE_EVENT_TYPE_MOVE_RELATIVE MOUSE_EVENT_TYPE  = 10 //MOVE_RELATIVE
)

var ALL_MOUSE_EVENT_TYPE protocol.IEnumCollection = []protocol.IEnum{MOUSE_EVENT_TYPE_NULL,MOUSE_EVENT_TYPE_DOWN,MOUSE_EVENT_TYPE_UP,MOUSE_EVENT_TYPE_PRESS,MOUSE_EVENT_TYPE_SCROLL_UP,MOUSE_EVENT_TYPE_SCROLL_DOWN,MOUSE_EVENT_TYPE_MOVE,MOUSE_EVENT_TYPE_ENTER,MOUSE_EVENT_TYPE_LEAVE,MOUSE_EVENT_TYPE_CANCEL,MOUSE_EVENT_TYPE_MOVE_RELATIVE}


var ENUM_MOUSE_EVENT_TYPE = protocol.NewEnumCollection([]MOUSE_EVENT_TYPE{MOUSE_EVENT_TYPE_NULL,MOUSE_EVENT_TYPE_DOWN,MOUSE_EVENT_TYPE_UP,MOUSE_EVENT_TYPE_PRESS,MOUSE_EVENT_TYPE_SCROLL_UP,MOUSE_EVENT_TYPE_SCROLL_DOWN,MOUSE_EVENT_TYPE_MOVE,MOUSE_EVENT_TYPE_ENTER,MOUSE_EVENT_TYPE_LEAVE,MOUSE_EVENT_TYPE_CANCEL,MOUSE_EVENT_TYPE_MOVE_RELATIVE})

func TO_MOUSE_EVENT_TYPE(s string)MOUSE_EVENT_TYPE{
	switch s {
	case "NULL":
		return MOUSE_EVENT_TYPE_NULL
	case "DOWN":
		return MOUSE_EVENT_TYPE_DOWN
	case "UP":
		return MOUSE_EVENT_TYPE_UP
	case "PRESS":
		return MOUSE_EVENT_TYPE_PRESS
	case "SCROLL_UP":
		return MOUSE_EVENT_TYPE_SCROLL_UP
	case "SCROLL_DOWN":
		return MOUSE_EVENT_TYPE_SCROLL_DOWN
	case "MOVE":
		return MOUSE_EVENT_TYPE_MOVE
	case "ENTER":
		return MOUSE_EVENT_TYPE_ENTER
	case "LEAVE":
		return MOUSE_EVENT_TYPE_LEAVE
	case "CANCEL":
		return MOUSE_EVENT_TYPE_CANCEL
	case "MOVE_RELATIVE":
		return MOUSE_EVENT_TYPE_MOVE_RELATIVE
	}
	return -1
}

func (this MOUSE_EVENT_TYPE) Enum()protocol.Enum{
	return protocol.Enum(this)
}


func (this MOUSE_EVENT_TYPE) ToString()string{
	switch this {
	case MOUSE_EVENT_TYPE_NULL:
		return "NULL"
	case MOUSE_EVENT_TYPE_DOWN:
		return "DOWN"
	case MOUSE_EVENT_TYPE_UP:
		return "UP"
	case MOUSE_EVENT_TYPE_PRESS:
		return "PRESS"
	case MOUSE_EVENT_TYPE_SCROLL_UP:
		return "SCROLL_UP"
	case MOUSE_EVENT_TYPE_SCROLL_DOWN:
		return "SCROLL_DOWN"
	case MOUSE_EVENT_TYPE_MOVE:
		return "MOVE"
	case MOUSE_EVENT_TYPE_ENTER:
		return "ENTER"
	case MOUSE_EVENT_TYPE_LEAVE:
		return "LEAVE"
	case MOUSE_EVENT_TYPE_CANCEL:
		return "CANCEL"
	case MOUSE_EVENT_TYPE_MOVE_RELATIVE:
		return "MOVE_RELATIVE"
	}
	return ""
}
