//this is a generate file,do not modify it!
package keys

import (
	"github.com/nomos/go-lokas/protocol"
)

type SCAN_CODE protocol.Enum 

const (
	SCAN_CODE_ESCAPE SCAN_CODE  = 1 //ESCAPE
	SCAN_CODE_N_1 SCAN_CODE  = 2 //1
	SCAN_CODE_N_2 SCAN_CODE  = 3 //2
	SCAN_CODE_N_3 SCAN_CODE  = 4 //3
	SCAN_CODE_N_4 SCAN_CODE  = 5 //4
	SCAN_CODE_N_5 SCAN_CODE  = 6 //5
	SCAN_CODE_N_6 SCAN_CODE  = 7 //6
	SCAN_CODE_N_7 SCAN_CODE  = 8 //7
	SCAN_CODE_N_8 SCAN_CODE  = 9 //8
	SCAN_CODE_N_9 SCAN_CODE  = 10 //9
	SCAN_CODE_N_0 SCAN_CODE  = 11 //0
	SCAN_CODE_MINUS SCAN_CODE  = 12 //MINUS
	SCAN_CODE_EQUAL SCAN_CODE  = 13 //EQUAL
	SCAN_CODE_BACKSPACE SCAN_CODE  = 14 //BACKSPACE
	SCAN_CODE_TAB SCAN_CODE  = 15 //TAB
	SCAN_CODE_Q SCAN_CODE  = 16 //Q
	SCAN_CODE_W SCAN_CODE  = 17 //W
	SCAN_CODE_E SCAN_CODE  = 18 //E
	SCAN_CODE_R SCAN_CODE  = 19 //R
	SCAN_CODE_T SCAN_CODE  = 20 //T
	SCAN_CODE_Y SCAN_CODE  = 21 //Y
	SCAN_CODE_U SCAN_CODE  = 22 //U
	SCAN_CODE_I SCAN_CODE  = 23 //I
	SCAN_CODE_O SCAN_CODE  = 24 //O
	SCAN_CODE_P SCAN_CODE  = 25 //P
	SCAN_CODE_LBRACE SCAN_CODE  = 26 //LBRACE
	SCAN_CODE_RBRACE SCAN_CODE  = 27 //RBRACE
	SCAN_CODE_ENTER SCAN_CODE  = 28 //ENTER
	SCAN_CODE_LCTRL SCAN_CODE  = 29 //LCTRL
	SCAN_CODE_A SCAN_CODE  = 30 //A
	SCAN_CODE_S SCAN_CODE  = 31 //S
	SCAN_CODE_D SCAN_CODE  = 32 //D
	SCAN_CODE_F SCAN_CODE  = 33 //F
	SCAN_CODE_G SCAN_CODE  = 34 //G
	SCAN_CODE_H SCAN_CODE  = 35 //H
	SCAN_CODE_J SCAN_CODE  = 36 //J
	SCAN_CODE_K SCAN_CODE  = 37 //K
	SCAN_CODE_L SCAN_CODE  = 38 //L;
	SCAN_CODE_SEMICOLON SCAN_CODE  = 39 //SEMICOLON
	SCAN_CODE_QUOTE SCAN_CODE  = 40 //QUOTE
	SCAN_CODE_TILDE SCAN_CODE  = 41 //TILDE
	SCAN_CODE_LSHIFT SCAN_CODE  = 42 //LSHIFT
	SCAN_CODE_BACKSLASH SCAN_CODE  = 43 //BackSlash
	SCAN_CODE_Z SCAN_CODE  = 44 //Z
	SCAN_CODE_X SCAN_CODE  = 45 //X
	SCAN_CODE_C SCAN_CODE  = 46 //C
	SCAN_CODE_V SCAN_CODE  = 47 //V
	SCAN_CODE_B SCAN_CODE  = 48 //B
	SCAN_CODE_N SCAN_CODE  = 49 //N
	SCAN_CODE_M SCAN_CODE  = 50 //M
	SCAN_CODE_COMMA SCAN_CODE  = 51 //COMMA
	SCAN_CODE_PERIOD SCAN_CODE  = 52 //PERIOD
	SCAN_CODE_SLASH SCAN_CODE  = 53 //SLASH
	SCAN_CODE_RSHIFT SCAN_CODE  = 54 //RSHIFT
	SCAN_CODE_KP_MULTIPLY SCAN_CODE  = 55 //KP_MULTIPLY
	SCAN_CODE_LALT SCAN_CODE  = 56 //LALT
	SCAN_CODE_SPACE SCAN_CODE  = 57 //SPACE
	SCAN_CODE_CAPSLOCK SCAN_CODE  = 58 //CAPSLOCK
	SCAN_CODE_F_1 SCAN_CODE  = 59 //F1
	SCAN_CODE_F_2 SCAN_CODE  = 60 //F2
	SCAN_CODE_F_3 SCAN_CODE  = 61 //F3
	SCAN_CODE_F_4 SCAN_CODE  = 62 //F4
	SCAN_CODE_F_5 SCAN_CODE  = 63 //F5
	SCAN_CODE_F_6 SCAN_CODE  = 64 //F6
	SCAN_CODE_F_7 SCAN_CODE  = 65 //F7
	SCAN_CODE_F_8 SCAN_CODE  = 66 //F8
	SCAN_CODE_F_9 SCAN_CODE  = 67 //F9
	SCAN_CODE_F_10 SCAN_CODE  = 68 //F10
	SCAN_CODE_NUMLOCK SCAN_CODE  = 69 //NUMLOCK
	SCAN_CODE_SCROLL_LOCK SCAN_CODE  = 70 //SCROLL_LOCK
	SCAN_CODE_KP_7 SCAN_CODE  = 71 //KP_7
	SCAN_CODE_KP_8 SCAN_CODE  = 72 //KP_8
	SCAN_CODE_KP_9 SCAN_CODE  = 73 //KP_9
	SCAN_CODE_KP_MINUS SCAN_CODE  = 74 //KP_MINUS
	SCAN_CODE_KP_4 SCAN_CODE  = 75 //KP_4
	SCAN_CODE_KP_5 SCAN_CODE  = 76 //KP_5
	SCAN_CODE_KP_6 SCAN_CODE  = 77 //KP_6
	SCAN_CODE_KP_PLUS SCAN_CODE  = 78 //KP_PLUS
	SCAN_CODE_KP_1 SCAN_CODE  = 79 //KP_1
	SCAN_CODE_KP_2 SCAN_CODE  = 80 //KP_2
	SCAN_CODE_KP_3 SCAN_CODE  = 81 //KP_3
	SCAN_CODE_KP_0 SCAN_CODE  = 82 //KP_0
	SCAN_CODE_KP_DECIMAL SCAN_CODE  = 83 //KP_DECIMAL
	SCAN_CODE_F_11 SCAN_CODE  = 84 //F11
	SCAN_CODE_F_12 SCAN_CODE  = 85 //F12
	SCAN_CODE_PRINT SCAN_CODE  = 86 //PRINT
	SCAN_CODE_PAUSE SCAN_CODE  = 87 //PAUSE
	SCAN_CODE_KP_ENTER SCAN_CODE  = 88 //KP_ENTER
	SCAN_CODE_RCTRL SCAN_CODE  = 89 //RCTRL
	SCAN_CODE_KP_DIVIDE SCAN_CODE  = 90 //KP_DIVIDE
	SCAN_CODE_RALT SCAN_CODE  = 91 //RALT
	SCAN_CODE_HOME SCAN_CODE  = 92 //HOME
	SCAN_CODE_UP SCAN_CODE  = 93 //UP
	SCAN_CODE_PGUP SCAN_CODE  = 94 //PGUP
	SCAN_CODE_LEFT SCAN_CODE  = 95 //LEFT
	SCAN_CODE_RIGHT SCAN_CODE  = 96 //RIGHT
	SCAN_CODE_END SCAN_CODE  = 97 //END
	SCAN_CODE_DOWN SCAN_CODE  = 98 //DOWN
	SCAN_CODE_PGDN SCAN_CODE  = 99 //PGDN
	SCAN_CODE_INSERT SCAN_CODE  = 100 //INSERT
	SCAN_CODE_DELETE SCAN_CODE  = 101 //DELETE
	SCAN_CODE_LWIN SCAN_CODE  = 102 //LWIN
	SCAN_CODE_RWIN SCAN_CODE  = 103 //RWIN
	SCAN_CODE_MENU SCAN_CODE  = 104 //MENU
	SCAN_CODE_POWER SCAN_CODE  = 105 //POWER
	SCAN_CODE_SLEEP SCAN_CODE  = 106 //SLEEP
	SCAN_CODE_WAKE SCAN_CODE  = 107 //WAKE
	SCAN_CODE_NEXTTRACK SCAN_CODE  = 108 //NEXTTRACK
	SCAN_CODE_PREVTRACK SCAN_CODE  = 109 //PREVTRACK
	SCAN_CODE_STOP SCAN_CODE  = 110 //STOP
	SCAN_CODE_PLAYPAUSE SCAN_CODE  = 111 //PLAYPAUSE
	SCAN_CODE_VOLUMEMUTE SCAN_CODE  = 112 //VOLUMEMUTE
	SCAN_CODE_VOLUMEUP SCAN_CODE  = 113 //VOLUMEUP
	SCAN_CODE_VOLUMEDOWN SCAN_CODE  = 114 //VOLUMEDOWN
	SCAN_CODE_LAUNCHMEDIASELECT SCAN_CODE  = 115 //LAUNCHMEDIASELECT
	SCAN_CODE_LAUNCHMAIL SCAN_CODE  = 116 //LAUNCHMAIL
	SCAN_CODE_LAUNCHAPP_1 SCAN_CODE  = 117 //LAUNCHAPP1
	SCAN_CODE_LAUNCHAPP_2 SCAN_CODE  = 118 //LAUNCHAPP2
	SCAN_CODE_BROWSERSEARCH SCAN_CODE  = 119 //BROWSERSEARCH
	SCAN_CODE_BROWSERHOME SCAN_CODE  = 120 //BROWSERHOME
	SCAN_CODE_BROWSERBACK SCAN_CODE  = 121 //BROWSERBACK
	SCAN_CODE_BROWSERFORWARD SCAN_CODE  = 122 //BROWSERFORWARD
	SCAN_CODE_BROWSERSTOP SCAN_CODE  = 123 //BROWSERSTOP
	SCAN_CODE_BROWSERREFRESH SCAN_CODE  = 124 //BROWSERREFRESH
	SCAN_CODE_BROWSERFAVORITES SCAN_CODE  = 125 //BROWSERFAVORITES
)

var ALL_SCAN_CODE protocol.IEnumCollection = []protocol.IEnum{SCAN_CODE_ESCAPE,SCAN_CODE_N_1,SCAN_CODE_N_2,SCAN_CODE_N_3,SCAN_CODE_N_4,SCAN_CODE_N_5,SCAN_CODE_N_6,SCAN_CODE_N_7,SCAN_CODE_N_8,SCAN_CODE_N_9,SCAN_CODE_N_0,SCAN_CODE_MINUS,SCAN_CODE_EQUAL,SCAN_CODE_BACKSPACE,SCAN_CODE_TAB,SCAN_CODE_Q,SCAN_CODE_W,SCAN_CODE_E,SCAN_CODE_R,SCAN_CODE_T,SCAN_CODE_Y,SCAN_CODE_U,SCAN_CODE_I,SCAN_CODE_O,SCAN_CODE_P,SCAN_CODE_LBRACE,SCAN_CODE_RBRACE,SCAN_CODE_ENTER,SCAN_CODE_LCTRL,SCAN_CODE_A,SCAN_CODE_S,SCAN_CODE_D,SCAN_CODE_F,SCAN_CODE_G,SCAN_CODE_H,SCAN_CODE_J,SCAN_CODE_K,SCAN_CODE_L,SCAN_CODE_SEMICOLON,SCAN_CODE_QUOTE,SCAN_CODE_TILDE,SCAN_CODE_LSHIFT,SCAN_CODE_BACKSLASH,SCAN_CODE_Z,SCAN_CODE_X,SCAN_CODE_C,SCAN_CODE_V,SCAN_CODE_B,SCAN_CODE_N,SCAN_CODE_M,SCAN_CODE_COMMA,SCAN_CODE_PERIOD,SCAN_CODE_SLASH,SCAN_CODE_RSHIFT,SCAN_CODE_KP_MULTIPLY,SCAN_CODE_LALT,SCAN_CODE_SPACE,SCAN_CODE_CAPSLOCK,SCAN_CODE_F_1,SCAN_CODE_F_2,SCAN_CODE_F_3,SCAN_CODE_F_4,SCAN_CODE_F_5,SCAN_CODE_F_6,SCAN_CODE_F_7,SCAN_CODE_F_8,SCAN_CODE_F_9,SCAN_CODE_F_10,SCAN_CODE_NUMLOCK,SCAN_CODE_SCROLL_LOCK,SCAN_CODE_KP_7,SCAN_CODE_KP_8,SCAN_CODE_KP_9,SCAN_CODE_KP_MINUS,SCAN_CODE_KP_4,SCAN_CODE_KP_5,SCAN_CODE_KP_6,SCAN_CODE_KP_PLUS,SCAN_CODE_KP_1,SCAN_CODE_KP_2,SCAN_CODE_KP_3,SCAN_CODE_KP_0,SCAN_CODE_KP_DECIMAL,SCAN_CODE_F_11,SCAN_CODE_F_12,SCAN_CODE_PRINT,SCAN_CODE_PAUSE,SCAN_CODE_KP_ENTER,SCAN_CODE_RCTRL,SCAN_CODE_KP_DIVIDE,SCAN_CODE_RALT,SCAN_CODE_HOME,SCAN_CODE_UP,SCAN_CODE_PGUP,SCAN_CODE_LEFT,SCAN_CODE_RIGHT,SCAN_CODE_END,SCAN_CODE_DOWN,SCAN_CODE_PGDN,SCAN_CODE_INSERT,SCAN_CODE_DELETE,SCAN_CODE_LWIN,SCAN_CODE_RWIN,SCAN_CODE_MENU,SCAN_CODE_POWER,SCAN_CODE_SLEEP,SCAN_CODE_WAKE,SCAN_CODE_NEXTTRACK,SCAN_CODE_PREVTRACK,SCAN_CODE_STOP,SCAN_CODE_PLAYPAUSE,SCAN_CODE_VOLUMEMUTE,SCAN_CODE_VOLUMEUP,SCAN_CODE_VOLUMEDOWN,SCAN_CODE_LAUNCHMEDIASELECT,SCAN_CODE_LAUNCHMAIL,SCAN_CODE_LAUNCHAPP_1,SCAN_CODE_LAUNCHAPP_2,SCAN_CODE_BROWSERSEARCH,SCAN_CODE_BROWSERHOME,SCAN_CODE_BROWSERBACK,SCAN_CODE_BROWSERFORWARD,SCAN_CODE_BROWSERSTOP,SCAN_CODE_BROWSERREFRESH,SCAN_CODE_BROWSERFAVORITES}

func TO_SCAN_CODE(s string)SCAN_CODE{
	switch s {
	case "ESCAPE":
		return SCAN_CODE_ESCAPE
	case "1":
		return SCAN_CODE_N_1
	case "2":
		return SCAN_CODE_N_2
	case "3":
		return SCAN_CODE_N_3
	case "4":
		return SCAN_CODE_N_4
	case "5":
		return SCAN_CODE_N_5
	case "6":
		return SCAN_CODE_N_6
	case "7":
		return SCAN_CODE_N_7
	case "8":
		return SCAN_CODE_N_8
	case "9":
		return SCAN_CODE_N_9
	case "0":
		return SCAN_CODE_N_0
	case "MINUS":
		return SCAN_CODE_MINUS
	case "EQUAL":
		return SCAN_CODE_EQUAL
	case "BACKSPACE":
		return SCAN_CODE_BACKSPACE
	case "TAB":
		return SCAN_CODE_TAB
	case "Q":
		return SCAN_CODE_Q
	case "W":
		return SCAN_CODE_W
	case "E":
		return SCAN_CODE_E
	case "R":
		return SCAN_CODE_R
	case "T":
		return SCAN_CODE_T
	case "Y":
		return SCAN_CODE_Y
	case "U":
		return SCAN_CODE_U
	case "I":
		return SCAN_CODE_I
	case "O":
		return SCAN_CODE_O
	case "P":
		return SCAN_CODE_P
	case "LBRACE":
		return SCAN_CODE_LBRACE
	case "RBRACE":
		return SCAN_CODE_RBRACE
	case "ENTER":
		return SCAN_CODE_ENTER
	case "LCTRL":
		return SCAN_CODE_LCTRL
	case "A":
		return SCAN_CODE_A
	case "S":
		return SCAN_CODE_S
	case "D":
		return SCAN_CODE_D
	case "F":
		return SCAN_CODE_F
	case "G":
		return SCAN_CODE_G
	case "H":
		return SCAN_CODE_H
	case "J":
		return SCAN_CODE_J
	case "K":
		return SCAN_CODE_K
	case "L;":
		return SCAN_CODE_L
	case "SEMICOLON":
		return SCAN_CODE_SEMICOLON
	case "QUOTE":
		return SCAN_CODE_QUOTE
	case "TILDE":
		return SCAN_CODE_TILDE
	case "LSHIFT":
		return SCAN_CODE_LSHIFT
	case "BackSlash":
		return SCAN_CODE_BACKSLASH
	case "Z":
		return SCAN_CODE_Z
	case "X":
		return SCAN_CODE_X
	case "C":
		return SCAN_CODE_C
	case "V":
		return SCAN_CODE_V
	case "B":
		return SCAN_CODE_B
	case "N":
		return SCAN_CODE_N
	case "M":
		return SCAN_CODE_M
	case "COMMA":
		return SCAN_CODE_COMMA
	case "PERIOD":
		return SCAN_CODE_PERIOD
	case "SLASH":
		return SCAN_CODE_SLASH
	case "RSHIFT":
		return SCAN_CODE_RSHIFT
	case "KP_MULTIPLY":
		return SCAN_CODE_KP_MULTIPLY
	case "LALT":
		return SCAN_CODE_LALT
	case "SPACE":
		return SCAN_CODE_SPACE
	case "CAPSLOCK":
		return SCAN_CODE_CAPSLOCK
	case "F1":
		return SCAN_CODE_F_1
	case "F2":
		return SCAN_CODE_F_2
	case "F3":
		return SCAN_CODE_F_3
	case "F4":
		return SCAN_CODE_F_4
	case "F5":
		return SCAN_CODE_F_5
	case "F6":
		return SCAN_CODE_F_6
	case "F7":
		return SCAN_CODE_F_7
	case "F8":
		return SCAN_CODE_F_8
	case "F9":
		return SCAN_CODE_F_9
	case "F10":
		return SCAN_CODE_F_10
	case "NUMLOCK":
		return SCAN_CODE_NUMLOCK
	case "SCROLL_LOCK":
		return SCAN_CODE_SCROLL_LOCK
	case "KP_7":
		return SCAN_CODE_KP_7
	case "KP_8":
		return SCAN_CODE_KP_8
	case "KP_9":
		return SCAN_CODE_KP_9
	case "KP_MINUS":
		return SCAN_CODE_KP_MINUS
	case "KP_4":
		return SCAN_CODE_KP_4
	case "KP_5":
		return SCAN_CODE_KP_5
	case "KP_6":
		return SCAN_CODE_KP_6
	case "KP_PLUS":
		return SCAN_CODE_KP_PLUS
	case "KP_1":
		return SCAN_CODE_KP_1
	case "KP_2":
		return SCAN_CODE_KP_2
	case "KP_3":
		return SCAN_CODE_KP_3
	case "KP_0":
		return SCAN_CODE_KP_0
	case "KP_DECIMAL":
		return SCAN_CODE_KP_DECIMAL
	case "F11":
		return SCAN_CODE_F_11
	case "F12":
		return SCAN_CODE_F_12
	case "PRINT":
		return SCAN_CODE_PRINT
	case "PAUSE":
		return SCAN_CODE_PAUSE
	case "KP_ENTER":
		return SCAN_CODE_KP_ENTER
	case "RCTRL":
		return SCAN_CODE_RCTRL
	case "KP_DIVIDE":
		return SCAN_CODE_KP_DIVIDE
	case "RALT":
		return SCAN_CODE_RALT
	case "HOME":
		return SCAN_CODE_HOME
	case "UP":
		return SCAN_CODE_UP
	case "PGUP":
		return SCAN_CODE_PGUP
	case "LEFT":
		return SCAN_CODE_LEFT
	case "RIGHT":
		return SCAN_CODE_RIGHT
	case "END":
		return SCAN_CODE_END
	case "DOWN":
		return SCAN_CODE_DOWN
	case "PGDN":
		return SCAN_CODE_PGDN
	case "INSERT":
		return SCAN_CODE_INSERT
	case "DELETE":
		return SCAN_CODE_DELETE
	case "LWIN":
		return SCAN_CODE_LWIN
	case "RWIN":
		return SCAN_CODE_RWIN
	case "MENU":
		return SCAN_CODE_MENU
	case "POWER":
		return SCAN_CODE_POWER
	case "SLEEP":
		return SCAN_CODE_SLEEP
	case "WAKE":
		return SCAN_CODE_WAKE
	case "NEXTTRACK":
		return SCAN_CODE_NEXTTRACK
	case "PREVTRACK":
		return SCAN_CODE_PREVTRACK
	case "STOP":
		return SCAN_CODE_STOP
	case "PLAYPAUSE":
		return SCAN_CODE_PLAYPAUSE
	case "VOLUMEMUTE":
		return SCAN_CODE_VOLUMEMUTE
	case "VOLUMEUP":
		return SCAN_CODE_VOLUMEUP
	case "VOLUMEDOWN":
		return SCAN_CODE_VOLUMEDOWN
	case "LAUNCHMEDIASELECT":
		return SCAN_CODE_LAUNCHMEDIASELECT
	case "LAUNCHMAIL":
		return SCAN_CODE_LAUNCHMAIL
	case "LAUNCHAPP1":
		return SCAN_CODE_LAUNCHAPP_1
	case "LAUNCHAPP2":
		return SCAN_CODE_LAUNCHAPP_2
	case "BROWSERSEARCH":
		return SCAN_CODE_BROWSERSEARCH
	case "BROWSERHOME":
		return SCAN_CODE_BROWSERHOME
	case "BROWSERBACK":
		return SCAN_CODE_BROWSERBACK
	case "BROWSERFORWARD":
		return SCAN_CODE_BROWSERFORWARD
	case "BROWSERSTOP":
		return SCAN_CODE_BROWSERSTOP
	case "BROWSERREFRESH":
		return SCAN_CODE_BROWSERREFRESH
	case "BROWSERFAVORITES":
		return SCAN_CODE_BROWSERFAVORITES
	}
	return -1
}

func (this SCAN_CODE) Enum()protocol.Enum{
	return protocol.Enum(this)
}


func (this SCAN_CODE) ToString()string{
	switch this {
	case SCAN_CODE_ESCAPE:
		return "ESCAPE"
	case SCAN_CODE_N_1:
		return "1"
	case SCAN_CODE_N_2:
		return "2"
	case SCAN_CODE_N_3:
		return "3"
	case SCAN_CODE_N_4:
		return "4"
	case SCAN_CODE_N_5:
		return "5"
	case SCAN_CODE_N_6:
		return "6"
	case SCAN_CODE_N_7:
		return "7"
	case SCAN_CODE_N_8:
		return "8"
	case SCAN_CODE_N_9:
		return "9"
	case SCAN_CODE_N_0:
		return "0"
	case SCAN_CODE_MINUS:
		return "MINUS"
	case SCAN_CODE_EQUAL:
		return "EQUAL"
	case SCAN_CODE_BACKSPACE:
		return "BACKSPACE"
	case SCAN_CODE_TAB:
		return "TAB"
	case SCAN_CODE_Q:
		return "Q"
	case SCAN_CODE_W:
		return "W"
	case SCAN_CODE_E:
		return "E"
	case SCAN_CODE_R:
		return "R"
	case SCAN_CODE_T:
		return "T"
	case SCAN_CODE_Y:
		return "Y"
	case SCAN_CODE_U:
		return "U"
	case SCAN_CODE_I:
		return "I"
	case SCAN_CODE_O:
		return "O"
	case SCAN_CODE_P:
		return "P"
	case SCAN_CODE_LBRACE:
		return "LBRACE"
	case SCAN_CODE_RBRACE:
		return "RBRACE"
	case SCAN_CODE_ENTER:
		return "ENTER"
	case SCAN_CODE_LCTRL:
		return "LCTRL"
	case SCAN_CODE_A:
		return "A"
	case SCAN_CODE_S:
		return "S"
	case SCAN_CODE_D:
		return "D"
	case SCAN_CODE_F:
		return "F"
	case SCAN_CODE_G:
		return "G"
	case SCAN_CODE_H:
		return "H"
	case SCAN_CODE_J:
		return "J"
	case SCAN_CODE_K:
		return "K"
	case SCAN_CODE_L:
		return "L;"
	case SCAN_CODE_SEMICOLON:
		return "SEMICOLON"
	case SCAN_CODE_QUOTE:
		return "QUOTE"
	case SCAN_CODE_TILDE:
		return "TILDE"
	case SCAN_CODE_LSHIFT:
		return "LSHIFT"
	case SCAN_CODE_BACKSLASH:
		return "BackSlash"
	case SCAN_CODE_Z:
		return "Z"
	case SCAN_CODE_X:
		return "X"
	case SCAN_CODE_C:
		return "C"
	case SCAN_CODE_V:
		return "V"
	case SCAN_CODE_B:
		return "B"
	case SCAN_CODE_N:
		return "N"
	case SCAN_CODE_M:
		return "M"
	case SCAN_CODE_COMMA:
		return "COMMA"
	case SCAN_CODE_PERIOD:
		return "PERIOD"
	case SCAN_CODE_SLASH:
		return "SLASH"
	case SCAN_CODE_RSHIFT:
		return "RSHIFT"
	case SCAN_CODE_KP_MULTIPLY:
		return "KP_MULTIPLY"
	case SCAN_CODE_LALT:
		return "LALT"
	case SCAN_CODE_SPACE:
		return "SPACE"
	case SCAN_CODE_CAPSLOCK:
		return "CAPSLOCK"
	case SCAN_CODE_F_1:
		return "F1"
	case SCAN_CODE_F_2:
		return "F2"
	case SCAN_CODE_F_3:
		return "F3"
	case SCAN_CODE_F_4:
		return "F4"
	case SCAN_CODE_F_5:
		return "F5"
	case SCAN_CODE_F_6:
		return "F6"
	case SCAN_CODE_F_7:
		return "F7"
	case SCAN_CODE_F_8:
		return "F8"
	case SCAN_CODE_F_9:
		return "F9"
	case SCAN_CODE_F_10:
		return "F10"
	case SCAN_CODE_NUMLOCK:
		return "NUMLOCK"
	case SCAN_CODE_SCROLL_LOCK:
		return "SCROLL_LOCK"
	case SCAN_CODE_KP_7:
		return "KP_7"
	case SCAN_CODE_KP_8:
		return "KP_8"
	case SCAN_CODE_KP_9:
		return "KP_9"
	case SCAN_CODE_KP_MINUS:
		return "KP_MINUS"
	case SCAN_CODE_KP_4:
		return "KP_4"
	case SCAN_CODE_KP_5:
		return "KP_5"
	case SCAN_CODE_KP_6:
		return "KP_6"
	case SCAN_CODE_KP_PLUS:
		return "KP_PLUS"
	case SCAN_CODE_KP_1:
		return "KP_1"
	case SCAN_CODE_KP_2:
		return "KP_2"
	case SCAN_CODE_KP_3:
		return "KP_3"
	case SCAN_CODE_KP_0:
		return "KP_0"
	case SCAN_CODE_KP_DECIMAL:
		return "KP_DECIMAL"
	case SCAN_CODE_F_11:
		return "F11"
	case SCAN_CODE_F_12:
		return "F12"
	case SCAN_CODE_PRINT:
		return "PRINT"
	case SCAN_CODE_PAUSE:
		return "PAUSE"
	case SCAN_CODE_KP_ENTER:
		return "KP_ENTER"
	case SCAN_CODE_RCTRL:
		return "RCTRL"
	case SCAN_CODE_KP_DIVIDE:
		return "KP_DIVIDE"
	case SCAN_CODE_RALT:
		return "RALT"
	case SCAN_CODE_HOME:
		return "HOME"
	case SCAN_CODE_UP:
		return "UP"
	case SCAN_CODE_PGUP:
		return "PGUP"
	case SCAN_CODE_LEFT:
		return "LEFT"
	case SCAN_CODE_RIGHT:
		return "RIGHT"
	case SCAN_CODE_END:
		return "END"
	case SCAN_CODE_DOWN:
		return "DOWN"
	case SCAN_CODE_PGDN:
		return "PGDN"
	case SCAN_CODE_INSERT:
		return "INSERT"
	case SCAN_CODE_DELETE:
		return "DELETE"
	case SCAN_CODE_LWIN:
		return "LWIN"
	case SCAN_CODE_RWIN:
		return "RWIN"
	case SCAN_CODE_MENU:
		return "MENU"
	case SCAN_CODE_POWER:
		return "POWER"
	case SCAN_CODE_SLEEP:
		return "SLEEP"
	case SCAN_CODE_WAKE:
		return "WAKE"
	case SCAN_CODE_NEXTTRACK:
		return "NEXTTRACK"
	case SCAN_CODE_PREVTRACK:
		return "PREVTRACK"
	case SCAN_CODE_STOP:
		return "STOP"
	case SCAN_CODE_PLAYPAUSE:
		return "PLAYPAUSE"
	case SCAN_CODE_VOLUMEMUTE:
		return "VOLUMEMUTE"
	case SCAN_CODE_VOLUMEUP:
		return "VOLUMEUP"
	case SCAN_CODE_VOLUMEDOWN:
		return "VOLUMEDOWN"
	case SCAN_CODE_LAUNCHMEDIASELECT:
		return "LAUNCHMEDIASELECT"
	case SCAN_CODE_LAUNCHMAIL:
		return "LAUNCHMAIL"
	case SCAN_CODE_LAUNCHAPP_1:
		return "LAUNCHAPP1"
	case SCAN_CODE_LAUNCHAPP_2:
		return "LAUNCHAPP2"
	case SCAN_CODE_BROWSERSEARCH:
		return "BROWSERSEARCH"
	case SCAN_CODE_BROWSERHOME:
		return "BROWSERHOME"
	case SCAN_CODE_BROWSERBACK:
		return "BROWSERBACK"
	case SCAN_CODE_BROWSERFORWARD:
		return "BROWSERFORWARD"
	case SCAN_CODE_BROWSERSTOP:
		return "BROWSERSTOP"
	case SCAN_CODE_BROWSERREFRESH:
		return "BROWSERREFRESH"
	case SCAN_CODE_BROWSERFAVORITES:
		return "BROWSERFAVORITES"
	}
	return ""
}
